<a href="https://colab.research.google.com/github/Camel-light/Assignments/blob/main/Copy_of_hommework_3_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#hide
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
from fastai.vision.all import *
from fastbook import *
fastbook.setup_book()

In [13]:
# Set the max_split_size_mb to a lower value (e.g. 100)
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb=100"

# Introduction to Artificial Neural Networks

Please read the introdcution of neuronal networks of the book *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow*, p. 299-316.

**Why have neural networks, even though they were invented early on, only now caught on?**


*In the '60s it became clear that the great hopes for ANNs would go unfulfilled, so funding went elsewhere.*

*The recent success of ANNs is due to multiple factors:*

*   *There is a huge amount of data available now (big data), to train ANNs.*
*   *There has been a tremendous increase in computation performance, as predicted by Moor's law.*
*   *The gaming industry led to the development of powerful GPU cards, which turned out to be useful for parallel computations such as those used to train ANNs.*
*   *Slight changes to the training algorithms led to vast improvements.*
*   *Some theoretical limits of ANNs, such as only finding the local optimum, rather than the absolute optimum using ANNs, revealed themselves as less problematic in practice than previously thought.*
*   *ANNs, seem to have entered a virtuous cycle of funding fulleing success, which in turn, fuels even more funding, etc…*


**What is a percepton and a threshold logic unit (TLU)? Try to define a linear function and a step function of your choice, use some values of your choice and explain what might be the result of the percepton. (maybe using max. two TLU's)**


*A perceptron is a simple ANN architecture, as invented by F. Rosenblatt in 1957. This model is composed of neurons called TLU - threshold logic unit. It's inputs are numbers and the outputs as well. It applies 2 functions to the inputs: first, a linear function of its inputs, associating a weight to each one. Then, it applies a step function to the result of the first function. It's parameters are the inputs's weights and the bias term. It is called threshold unit, because the step function outputs an output, depending on whether the linear function crosses a threshold.*

*Let's imagine a first TLU composed this way:*

*Input function: 2x_1 + 1x_2 + b*
*Step function: heaviside(z)=*

*0 if z < 0*

*1 if z ≥ 0*

*Second TLU composed this way:*

*Input function: 2x_1 + 2x_2 + b*

*Step function:  sgn(z)=*

*−1 if z < 0*

*0 if z = 0*

*+1 if z > 0*

*The perceptron takes 2 inputs. If we give it x_1 = 1 & x_2 = 0 it will return:*

*First TLU:  2 * (1) + 1 * (0) = 2  =>  heaviside(2) = 1*

*Second TLU: 2 * (1) + 2 * (0) = 2  =>  sgn(2) = 1*

*The output is:*

*TLU_1 = 1*

*TLU_2 = 1*


**What is a fully connected layer and a output layer?**

*A fully connected layer is a layer of TLUs in a Perceptron, where every input is connected to every TLU, it is also called a dense layer. This means that the input vector is multiplied by a weight matrix to produce the output vector. The inputs are called input layer and the output layer is the last layer of the neural network, which produces the output, in this case the layer of threshold logic units.*

**Why can we easily combine the equations of multiple instances into a fully connected layer?**

*If we consider the equation for computing the outputs of a fully connected layer: ℎ[W,b (X)] = ϕ(XW + b)*

*With X and W the instances and weights matrices respectively, and b the bias term vector, we can notice that there is an addition of a vector (b) to a matrix (). This is formally not allowed in mathematics, however in data science "broadcasting" is allowed. It means adding it to every row in the matrix. So we add the bias term to every row of the matrix resulting from the XW multiplication, which resultis in the bias added to every instance in the output. Then the function phi is applied to every instance.*


**What problem did Marvin Minsky and Seymour Paper highlight that perceptrons could not solve? What is a possible solution?**

*They showed that perceptrons are unable to solve simple problems, such as the exclusive OR (XOR) classification problem. One solution, is to stack perceptrons together in a  multi layer perceptron MLP. Now it is possible to solve the XOR problem. *

**What is a deep neuronal network? What are hidden layers? What means feedforward neural network (FNN).**

*A deep neural network is a network with a deep stack of hidden layers. The definition of "deep" is quite fuzzy, in the '90s even more than 2 hidden layers were defined as deep, while nowadays they can have many more.Feed forward neural network (FNN) is a network where the flow goes only in one direction, from the inputs to the outputs. It means there are no loops in the network, and the output of one layer does not influence the same or previous layers.*

**Try to explain how backpropagation works! (In Addition, you can have a look to the following example, which tries manually to compute the backprogation of a simple linear network. https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/ OR you can also read through the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy))**

*Formally, backpropagation can be described as a specific algorithm for reverse pass. In two passes it is able to compute the gradients (partial derivatives) of the loss function for every parameter. It computes how much each bias and weight contributes to the total error. The tuning of the parameters is done by gradient descent. It will eventually reach a minimum.*

*In more detail, it takes a small batch of instances and goes through the training set multiple times, each iteration is called an “epoch”. All the inputs run from the first, through the hidden layers up to the output layer. Just like in the normal case, but it also saves the activations of each layer. This is called “forward pass”. The network computes the total loss, as the error it makes when computing the output. The total loss is a function of the errors that depends on the chosen loss function. Then it calculates how much each bias and weight to the output neuron contributed to the error. This is done by applying the chain rule of calculus, taking the partial derivatives. Then it calculates how much of this error came from the previous layer. It then does this until it reaches the input layer. This is the “backward propagation”. By computing the gradients of the loss function with respect to each weight and bias, it determines how much each parameter contributes to the total error. It calculates the negative gradient, which tells how much each parameter should change to reduce the cost function. It also uses it to update each parameter by subtracting a fraction of it (the learning rate) from its current value. This is called gradient descent.*

**Why do we need activation functions, wouldn't it be easier just using linear functions?**

*Ultimately, we need activation functions, to introduce non-linearity between the input and the output. This is necessary because a linear combination of linear functions is always a linear function, and so even with multiple layers, combining many linear functions would result just in a network capable of approximating linear relations, but not non-linear ones. To describe complex phenomena, we need to be able to describe non-linear relations.*
## Ideas for the learning portfolio: 

1) For example, you could train a single TLU to classify iris flowers based on petal length and width in the !!!pyTorch!! environment.

2) You could add to our king county housepricing ML project a neuronal network and compare it to the other models. 

In [14]:
# from sklearn import datasets
# iris = datasets.load_iris()

# A traditional approach: training a digit classifier and learning pyTorch tensors.

For this assignment, I ask you to read the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy) to the beginning of the chapter *Stochastic Gradient Descent (SGD)*. 

First, try to summarize what we know about pyTorch tensors by trying to predict whether we have a 1 or a 7 in the MNIST dataset using a traditional rule-based programming approach. Therefore use pyTorch tensors for the entire tasks and fulfill the following steps:

1) Randomly split the MNIST dataset (1 and 7) into a training dataset and a test dataset in a ratio of 80:20.

In [15]:
# Download MNIST FULL.
path = untar_data(URLs.MNIST)
Path.BASE_PATH = path
path.ls()

(#2) [Path('testing'),Path('training')]

In [16]:
# Check ls in training folder.
(path/'training').ls()

(#10) [Path('training/6'),Path('training/9'),Path('training/2'),Path('training/7'),Path('training/5'),Path('training/0'),Path('training/3'),Path('training/4'),Path('training/8'),Path('training/1')]

In [17]:
# Save the ones and the sevens.
ones = (path/'training'/'1').ls().sorted()
sevens = (path/'training'/'7').ls().sorted()
print(ones)
print(sevens)

[Path('training/1/10006.png'), Path('training/1/10007.png'), Path('training/1/1002.png'), Path('training/1/10020.png'), Path('training/1/10027.png'), Path('training/1/1003.png'), Path('training/1/10040.png'), Path('training/1/10048.png'), Path('training/1/10058.png'), Path('training/1/10067.png'), Path('training/1/10068.png'), Path('training/1/10085.png'), Path('training/1/10098.png'), Path('training/1/10110.png'), Path('training/1/10118.png'), Path('training/1/1012.png'), Path('training/1/10123.png'), Path('training/1/10129.png'), Path('training/1/10134.png'), Path('training/1/10136.png'), Path('training/1/10139.png'), Path('training/1/10145.png'), Path('training/1/10152.png'), Path('training/1/10156.png'), Path('training/1/10157.png'), Path('training/1/10169.png'), Path('training/1/1017.png'), Path('training/1/10180.png'), Path('training/1/102.png'), Path('training/1/10205.png'), Path('training/1/10220.png'), Path('training/1/10223.png'), Path('training/1/10239.png'), Path('training/

In [18]:

# Look at a picture of a 1 in the 1s folder.
im1_path = ones[1]
im1 = Image.open(im1_path)
im1

In [19]:
# Look at a picture of a 7 in the 7s folder.
im7_path = sevens[1]
im7 = Image.open(im7_path)
im7

In [20]:
# Look at it like a computer (1 - array, 7 - tensor).
print(array(im1)[:,:])
print(tensor(im7)[:,:])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  13 212 253  56   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  24 252 252 139   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 108 252 252  45   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 233 252 195   9   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  53 253 252  79   

In [21]:
import numpy as np
from PIL import Image
from sklearn.model_selection import train_test_split

# Define a function to load an image as a numpy array.
def load_image(path):
  img = Image.open(path)
  return np.array(img)

# Images of ones and sevens as numpy arrays.
X_ones = np.array([load_image(p)for p in ones])

X_sevens = np.array([load_image(p) for p in sevens])

# Create  labels for ones and sevens
y_ones = np.full(len(X_ones), 1)
y_sevens = np.full(len(X_sevens), 7)

# Concatenate the images and labels of ones and sevens
X = np.concatenate([X_ones, X_sevens])
y = np.concatenate([y_ones, y_sevens])

# Split the dataset into 80% train and 20% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print the sizes of the subsets
print(f"Train set size: {X_train.shape}")
print(f"Test set size: {X_test.shape}")



Train set size: (10405, 28, 28)
Test set size: (2602, 28, 28)


In [22]:
import torch

# Convert the train and test sets from numpy arrays to tensors
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

# Print the types of the subsets
print(f"Train set type: {type(X_train)}")
print(f"Test set type: {type(X_test)}")

Train set type: <class 'torch.Tensor'>
Test set type: <class 'torch.Tensor'>


In [23]:
# Scale down the values from up to 256, to 0 - 1
X_train = X_train.float() / 255
X_test = X_test.float() / 255
y_train = y_train.float() /255
y_test = y_test.float() /255

# Print the min and max values of the subsets
print(f"Train set min: {X_train.min()}")
print(f"Train set max: {X_train.max()}")
print(f"Test set min: {X_test.min()}")
print(f"Test set max: {X_test.max()}")

print(f"Train labels min: {y_train.min()}")
print(f"Train labels max: {y_train.max()}")
print(f"Test labels min: {y_test.min()}")
print(f"Test labels max: {y_test.max()}")

Train set min: 0.0
Train set max: 1.0
Test set min: 0.0
Test set max: 1.0
Train labels min: 0.003921568859368563
Train labels max: 0.027450980618596077
Test labels min: 0.003921568859368563
Test labels max: 0.027450980618596077


2) Instead of using an optimal 1 or 7 with the mean over the training dataset, try to calculate the sum of the distances to all instances in the training set for each instance in the test dataset. You can use the L2 norm. 

In [24]:
'''
# take two image tensors as input and returns the L2 norm of their difference.
def l2_norm(image1, image2):
  # Compute the difference between the two images.
  diff = image1 - image2
  
  # Compute the square of each element in the difference.
  square = torch.pow(diff, 2)
  
  # Compute the sum of all the squares.
  total = torch.sum(square)
  
  # Compute the square root of the total.
  root = torch.sqrt(total)
  
  # Return the root as the L2 norm.
  return root

# Store the sums of distances.
sums = []

# Loop over each image tensor in the test set.
for test_image in X_test:
  # Create a variable to store the sum of distances for this test image.
  sum = 0
  
  # Loop over each image tensor in the train set.
  for train_image in X_train:
    # Compute the L2 norm between the test image and the train image using the function abave.
    norm = l2_norm(test_image, train_image)
    
    # Add norm to the sum
    sum += norm
  
  # Append the sum to the tensor.
  sums.append(sum)

# Print the sums of distances for each test image
print(sums)
'''

'\n# take two image tensors as input and returns the L2 norm of their difference.\ndef l2_norm(image1, image2):\n  # Compute the difference between the two images.\n  diff = image1 - image2\n  \n  # Compute the square of each element in the difference.\n  square = torch.pow(diff, 2)\n  \n  # Compute the sum of all the squares.\n  total = torch.sum(square)\n  \n  # Compute the square root of the total.\n  root = torch.sqrt(total)\n  \n  # Return the root as the L2 norm.\n  return root\n\n# Store the sums of distances.\nsums = []\n\n# Loop over each image tensor in the test set.\nfor test_image in X_test:\n  # Create a variable to store the sum of distances for this test image.\n  sum = 0\n  \n  # Loop over each image tensor in the train set.\n  for train_image in X_train:\n    # Compute the L2 norm between the test image and the train image using the function abave.\n    norm = l2_norm(test_image, train_image)\n    \n    # Add norm to the sum\n    sum += norm\n  \n  # Append the sum to 

Aborted after 9 minutes because life is short. Let's try to do it faster by avoiding loops, and take full advantage of the libraries written in C.

As we are multiplying matrices for the entire test and training sets. The number of element-wise multiplications depends on the size of the difference tensor, which is equal to the size of the test set * the size of the train set * the size of an image.

In this case, we have to do 2602 * 10405 * 28 * 28 = 20561239200 element-wise multiplications.

The number of scalar multiplications depends on the size of the norms tensor, which is equal to the size of the test set times the size of the train set. In this case, we have to do 2602 * 10405 = 27072310 scalar multiplications.

The total number of multiplications is the sum of these two numbers. In this case, we have to do 20561239200 + 27072310 = 20588311510 multiplications. 😲

Now, we will try to use the power of the GPU, check if it is available, and reduce the size of the tensors,  split them into smaller chunks before processing them. Also, set the max_split_size_mb environment variable to a lower value to avoid memory fragmentation.

In [ ]:
# Reduce the size of your tensors by taking a subset of the data (e.g. 1000 images)
X_train = X_train[:1000]
X_test = X_test[:1000]

# Check if cuda is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Move the tensors to the device
X_train = X_train.to(device)
X_test = X_test.to(device)

# Create a new dimension for the test set
X_test_new = X_test.unsqueeze(1)

# Broadcast the test set to match the shape of the train set
X_test_new = X_test_new.expand(-1, X_train.shape[0], -1, -1)

# Compute the difference between the test set and the train set
diff = X_test_new - X_train

# Compute the L2 norm along the last two dimensions
norms = torch.norm(diff, dim=(-1,-2))

# Sum up the norms along the train dimension
sums = torch.sum(norms, dim=1)

# Move the sums tensor back to the CPU before printing it
sums = sums.to("cpu")
print(sums)

From crashing the ram, from 9+ minutes runtime in python, to 0.016 seconds runtime, something seems to have worked!

3) For each instance in the test set, decide if it is a 1 or 7 and calculate the precision.

Do we get a similar good result?

I got around 1 for both. It crashes many times, rarely it works.


In [ ]:
# Calculate precision of each instance in test set
precision = []
for i in range(len(sums)):
    if i == 0:
        precision.append(sums[i]/sums[i+1])
    elif i == len(sums)-1:
        precision.append(sums[i]/sums[i-1])
    else:
        precision.append((sums[i]/sums[i-1] + sums[i]/sums[i+1])/2)

# Decide if it is a 1 or 7 and calculate precision
ones_precision = []
sevens_precision = []
for i in range(len(precision)):
    if i < 500:
        ones_precision.append(precision[i])
    else:
        sevens_precision.append(precision[i])

ones_precision_mean = sum(ones_precision)/len(ones_precision)
sevens_precision_mean = sum(sevens_precision)/len(sevens_precision)

print(f"Precision for ones: {ones_precision_mean}")
print(f"Precision for sevens: {sevens_precision_mean}")

# Stochastic Gradient Descent (SGD)

For this exercise I ask you to read the chapter Stochastic Gradient Descent (SGD) from the Google Colab 04_mnist_basics.ipynb in paralell. The chapter starts with a single TLU, compare p. 304 in "Hands on Machine Learning". Go through all 7 steps which are an easy example of how Stochastic Gradient Descent works.

Our goal is to train a single TLU, which can decide if one number is larger then the other one. Therefore we create 100 random pairs with pyTorch and create a target vector which is eather 1 or 0.


In [26]:
x = torch.randn((100, 2))
y = torch.where(x[:,0] > x[:,1], 1.0, 0.0)
print(x)
print(y)

tensor([[ 1.9269e+00,  1.4873e+00],
        [ 9.0072e-01, -2.1055e+00],
        [ 6.7842e-01, -1.2345e+00],
        [-4.3067e-02, -1.6047e+00],
        [-7.5214e-01,  1.6487e+00],
        [-3.9248e-01, -1.4036e+00],
        [-7.2788e-01, -5.5943e-01],
        [-7.6884e-01,  7.6245e-01],
        [ 1.6423e+00, -1.5960e-01],
        [-4.9740e-01,  4.3959e-01],
        [-7.5813e-01,  1.0783e+00],
        [ 8.0080e-01,  1.6806e+00],
        [ 1.2791e+00,  1.2964e+00],
        [ 6.1047e-01,  1.3347e+00],
        [-2.3162e-01,  4.1759e-02],
        [-2.5158e-01,  8.5986e-01],
        [-1.3847e+00, -8.7124e-01],
        [-2.2337e-01,  1.7174e+00],
        [ 3.1888e-01, -4.2452e-01],
        [ 3.0572e-01, -7.7459e-01],
        [-1.5576e+00,  9.9564e-01],
        [-8.7979e-01, -6.0114e-01],
        [-1.2742e+00,  2.1228e+00],
        [-1.2347e+00, -4.8791e-01],
        [-9.1382e-01, -6.5814e-01],
        [ 7.8024e-02,  5.2581e-01],
        [-4.8799e-01,  1.1914e+00],
        [-8.1401e-01, -7.359

Your task is to create a function f that is a single TLU, meaning that it summarizes x with weights a, b, c:

$ax_0+bx_1+c$

In Addition we are using a *sigmoid()* function as step function.

$f = \text{sigmoid}(ax_0+bx_1+c)$

$f(x)={\frac {1}{1+e^{-x}}}$

In [27]:
def f(x, params):
    a,b,c = params
    return 1 / (1 + torch.exp(-(a*x[:,0] + b*x[:,1] + c)))
    
print(f(x, [3,-2,1]))

tensor([9.7825e-01, 9.9963e-01, 9.9595e-01, 9.8338e-01, 1.0417e-02, 9.3275e-01, 4.8381e-01, 5.5650e-02, 9.9807e-01, 2.0240e-01, 3.1340e-02, 5.1029e-01, 9.0418e-01, 5.4039e-01, 5.5518e-01, 1.8627e-01,
        1.9599e-01, 4.2909e-02, 9.4298e-01, 9.6971e-01, 3.4567e-03, 3.9244e-01, 8.5119e-04, 1.5083e-01, 3.9527e-01, 5.4549e-01, 5.4851e-02, 5.0749e-01, 3.6203e-02, 3.6780e-01, 4.8218e-02, 4.8655e-03,
        9.7398e-01, 9.9865e-01, 9.1943e-01, 8.8385e-03, 3.6259e-01, 5.7866e-01, 9.8216e-01, 1.6023e-02, 8.4685e-01, 1.3572e-01, 8.2626e-01, 9.8688e-01, 9.8515e-01, 3.3693e-02, 7.5066e-02, 9.8266e-01,
        5.5022e-04, 9.6431e-01, 8.5268e-01, 9.9395e-01, 2.5706e-01, 8.6499e-01, 3.2047e-01, 8.3248e-01, 4.0449e-02, 1.4785e-01, 9.5240e-01, 2.2740e-01, 6.1781e-01, 4.6733e-01, 9.7354e-01, 9.1190e-01,
        9.9159e-01, 2.5932e-01, 6.4229e-02, 8.5963e-01, 9.8772e-01, 1.8919e-03, 1.0045e-01, 8.8380e-02, 2.1146e-02, 9.5056e-01, 9.0284e-01, 1.9671e-01, 5.2774e-01, 2.6425e-02, 3.6649e-03, 1.4614e-02,


In addition to our TLU function, we need a loss function. Your task is to implement a absolute difference loss function, $∑|x_i-y_i|$, which counts the number of wrong guesses.

In [28]:
def mae(preds, targets): return (preds-targets).abs().mean()

Try to train your single TLU with the absolute difference loss function, use the following code. Choose an appropriate step weight `lr` and try to explain what is happing in each line.

In [32]:
lr = 1
params = torch.randn(3).requires_grad_()

def apply_step(params, prn=True):
    preds = f(x, params)
    loss = mae(preds, y)
    loss.backward()
    params.data -= lr * params.grad.data
    params.grad = None
    if prn: print(params);print(loss.item())
    return preds


for i in range(50): apply_step(params)

tensor([0.5253, 1.5748, 0.3741], requires_grad=True)
0.5668485760688782
tensor([0.6434, 1.5260, 0.3524], requires_grad=True)
0.5502452254295349
tensor([0.7597, 1.4714, 0.3281], requires_grad=True)
0.53336501121521
tensor([0.8740, 1.4110, 0.3015], requires_grad=True)
0.516190767288208
tensor([0.9859, 1.3450, 0.2727], requires_grad=True)
0.4987139403820038
tensor([1.0951, 1.2735, 0.2422], requires_grad=True)
0.4809423089027405
tensor([1.2013, 1.1968, 0.2102], requires_grad=True)
0.4629126787185669
tensor([1.3042, 1.1154, 0.1774], requires_grad=True)
0.4447017014026642
tensor([1.4032, 1.0300, 0.1440], requires_grad=True)
0.42643052339553833
tensor([1.4980, 0.9412, 0.1108], requires_grad=True)
0.40826255083084106
tensor([1.5883, 0.8501, 0.0782], requires_grad=True)
0.39039409160614014
tensor([1.6738, 0.7576, 0.0466], requires_grad=True)
0.37303709983825684
tensor([1.7543, 0.6648, 0.0165], requires_grad=True)
0.3563927114009857
tensor([ 1.8298,  0.5724, -0.0119], requires_grad=True)
0.34062

    lr = 1
This line sets the step weight or learning rate to 1. The learning rate determines how big the steps are during optimization, and it's a number we choose to control how fast the model learns. Shold not be too large because it might diverge, or skip the minimum, if too small it will take a long time.

    params = torch.randn(3).requires_grad_()
This line randomly initializes the parameters of the TLU model. Parameters must be assigned randomly or taken from another model in the case of *transfter learning*. The *requires_grad_()* function tells PyTorch to compute gradients for these parameters during training, so we can optimize them later.

    def apply_step(params, prn=True):
This line defines a function called *apply_step()* that takes the current parameters params as input and an optional flag prn to decide whether to print the updated parameters and loss value at each step.

    preds = f(x, params)
This line uses the current parameters to make predictions for the input data x using the TLU activation function we defined earlier.

    loss = mae(preds, y)
This line calculates the mean absolute error (MAE) loss between the predicted outputs preds and the actual targets y. Loss is a measure of how far off our predictions are from the true values.

    loss.backward()
This line computes the gradients of the loss with respect to the parameters using backpropagation. Gradients tell us how the loss changes as we tweak the parameters, so we can update them to minimize the loss.

    params.data -= lr * params.grad.data
This line updates the parameters by subtracting a portion of the gradients from their current values. The learning rate determines how big the steps are, so a larger learning rate makes bigger updates and vice versa. This step is like fine-tuning the weights to make the model better.

    params.grad = None
This line resets the gradients to zero after updating the parameters, so they can be computed fresh in the next iteration.

    if prn: print(params);print(loss.item())
This line is optional and prints the updated parameters and the current loss value if the prn = True. It helps us monitor the training progress.

    return preds
This line returns the predicted outputs of the TLU model after the update.

    for i in range(50): apply_step(params)
This is a loop that iterates 50 times and calls the apply_step() function at each iteration. This is the main training loop where the model learns.

Write a line of code that counts the number of wrong predictions, rounding your predictions with *round()*.

In [30]:
preds = f(x, params)
num_wrong_preds = (torch.round(preds) != y).sum().item()
num_wrong_preds

1

By adjusting the epochs, we can note that for 50 epochs we got 1 wrong prediction, and for exaple, for 3 epochs we got 56 wrong predictions. Even with 10.000 epochs, we still got 1 wrong prediction.